version: '3.4'

services:
  pgsql_asp:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'pgsql_asp'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: rest_with_asp_net_udemy
    mem_limit:  512m  
    
  rest-with-asp-net-udemy:
    image: rest-with-asp-net-udemy
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile  
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - pgsql_asp

volumes:
  pg-data:
  
